### ISSUE TITLE
Question: Popup messages

### ISSUE THREAD

**Issue by AckslD** [antonk52/bad-practices.nvim#2]
Hey! Not an issue (hope you don't mind :)) but during the VimConf I saw someone using `bad-practises` (I think but I don't remember which talk) but the messages came up in a floating notification window ontop to the right. Any idea how that was accomplished?

I looked a bit at the code here but can only see calls to `echohl`, so maybe this was forked or some other plugin was used?

**Comment by lucax88x** [comment]
@AckslD  Was wondering the same.

this is the video btw https://www.youtube.com/watch?v=pkyurqHhlXI

Maybe there's some plugin that overrides all messages to be in this floating error?

**Comment by lucax88x** [comment]
Something like this one https://github.com/rcarriga/nvim-notify

**Comment by antonk52** [comment]
Hello and thanks for the question @AckslD 
@lucax88x is correct. If you make sure that you are on the latest commit of bad-practices.nvim and have vim-notify installed, it’s floating windows will be used instead of printing messages to the status line. There’s a mention of this functionality in the readme for the repo under the gif
https://github.com/antonk52/bad-practices.nvim#bad-practicesnvim

Does this answer your question?

**Comment by AckslD** [comment]
Cool, thanks @antonk52 and @lucax88x :)
